### ISSUE TITLE
Events: whole day setting is not reflected for display of date

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#121]
maybe some tiles should have a display only in edit-mode flag

**Comment by datakurre** [comment]
Hmm... This is probably because whole date is separate field and the date fields display widget lnows nothing about. Maybe both desing problem with and schema / z3c.form limitation with this kind of date field usage.

Only sane fix would probably be to have dedicated tile for datetime periods, yet making ttile's edit form edit content fields may not be trivial.

**Comment by datakurre** [comment]
Part of https://github.com/plone/plone.app.mosaic/issues/127
