### ISSUE TITLE
Do not override "view" view

### ISSUE THREAD

**Issue by vangheem** [plone/plone.app.mosaic#130]
Is this really necessary anymore. Seems a bit dangerous and we can just provide our own view name now as we're not doing the tricky overriding that we were previously doing.

@datakurre what do you think?

**Comment by vangheem** [comment]
Or we need to ship with layouts that make sense for all types. Or again, we just should only enable mosaic on the types we have layouts for. See https://github.com/plone/plone.app.mosaic/blob/master/src/plone/app/mosaic/setuphandlers.py#L70

**Comment by datakurre** [comment]
The main reason for "view" was to make "Mosaic layout" the default view for new TTW content types. (Otherwise it should be manually added into new types through ZMI portal_types.)

Renaming is something to be made now before plone.app.blocks 3.0.0. The view is defined in plone.app.blocks. Should it be "layout_view"?

Overriding "view" was completely unrelated to the previous static layout implementatino (++layout++stuff). Also, all default types have something other than "view" as their default views, but I agree that overriding "view" may hide default views of custom file system content types.

**Comment by datakurre** [comment]
@vangheem Would "layout_view" be ok? I could fix that and then make plone.app.blocks release? Also, are you planning to work something into Mosaic this or next week, or should I start wrapping it into a beta release?

**Comment by vangheem** [comment]
"layout_view" is fine.

I'd like to find a solution for "Could not find layout for content" happening on a lot of the content right now.

I added support of being able to provide default layout in the registry for types.

FYI, where I'm seeing the potential issue right now is File and Image types. If you use the uploader in folder contents, you don't go through the add form for creating content and selecting layout. I think we should disable mosaic on File and Image types at the very least.

Other things I would like to do though:
- figure out a decent UI for being able to save custom layouts as new layouts
- be able to hide layouts, UI would be in layout editor page. Right now, there are 6 layouts OOTB and many are duplicates to give examples. We should clean that up.

**Comment by datakurre** [comment]
Nathan Van Gheem wrote:
> "layout_view" is fine.

Ok. I'll take care of that. Upgrade step will just add "layout_view", 
because it may not be safe to remove "view" and display menu will hide 
unavailable options anyways.

> I'd like to find a solution for "Could not find layout for content"
> happening on a lot of the content right now.

> I added support of being able to provide default layout in the registry
> for types.

So, the "Could not find layout for content" error layout should be 
overridable with some browser layer specific registration in 
plone.app.mosaic with something working for all types? It could not be 
much more than title + description (basically 
++contentlayout++default/basic.html).

> FYI, where I'm seeing the potential issue right now is File and Image
> types. If you use the uploader in folder contents, you don't go through
> the add form for creating content and selecting layout. I think we
> should disable mosaic on File and Image types at the very least.

Disabling Mosaic (not adding behavior or layout_view) for File and Image 
types sounds right. Doesn't make much sense there.

> Other things I would like to do though:
>
>   * figure out a decent UI for being able to save custom layouts as new
>     layouts

+1

>   * be able to hide layouts, UI would be in layout editor page. Right
>     now, there are 6 layouts OOTB and many are duplicates to give
>     examples. We should clean that up.

There should be only one duplicate now. I changed setuphandlers to only 
create one TTW layout as an example. Also, I don't really like the event 
layout (it was mainly an example about, how readonly tiles currently work).

If you figure out UI to save layouts, maybe we could ship with only 
basic and document layouts and now TTW layout examples (making most 
types show only basic layout by default) and rest could be created with 
editor and saved with your UI. Then there would be no need to hide 
layouts right now.

**Comment by datakurre** [comment]
Asko Soukka wrote:
> So, the "Could not find layout for content" error layout should be
> overridable with some browser layer specific registration in
> plone.app.mosaic with something working for all types? It could not be
> much more than title + description (basically
> ++contentlayout++default/basic.html).

Oh, forget that. Why not just check for 
"plone.app.blocks.default_layout" after content type specific defaults 
in blocks and set that into default/basic.html in Mosaic?

**Comment by vangheem** [comment]
that'd work too.

**Comment by datakurre** [comment]
Fixed in #131
