### ISSUE TITLE
layout specific classes on body tag

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#132]
for better styling it would nice to have layout specific classes for view and edit on the body tag 

something like:
```
<body class="portaltype-document mosaic-view myfancy-mosaiclayout" ...
<body class="portaltype-document mosaic-edit myfancy-mosaiclayout" ...
```

**Comment by datakurre** [comment]
Fixed in https://github.com/plone/plone.app.blocks/commit/b389f3a4334f570837dd535e35e0e0b800d99e88 and https://github.com/plone/plone.app.mosaic/commit/a5e53516e84d8f8cbd83a937c3c3dcbd55d8dd17

Now content with Mosaic layout enabled have body class ``template-layout`` and ``layout-foo-bar`` or ``layout-custom`` (foo-bar gets generated from ++contentlayout++foo/bar.html).

This requires releases for both plone.app.blocks and plone.app.mosaic. I'll do those once Plone 5 final is out and it is confirmed that Mosaic works on it.

**Comment by agitator** [comment]
thanx!
