### ISSUE TITLE
only schema based tiles are being saved for centrally manage layouts?

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#157]
an additional richtext tile is not being saved without customizing the layout?

**Comment by datakurre** [comment]
Yes. This is by design. @vangheem created persistent rich text tile variant (``plone.app.standardtiles.rawhtml``) to allow customizable rich text tiles in centrally managed layouts. It's not available in insert-menu, because the default rich text tile has better performance (no additional persistent data to load). Maybe some optional magic could transform static rich text tiles into editable ones also with centrally managed layouts. Currently the only option is to add those tiles manually into layout HTML (``href="./@@plone.app.standardtiles.rawhtml/someid?content=<p>Placeholder</p>``).

**Comment by agitator** [comment]
```
      <div class="movable removable mosaic-tile mosaic-plone.app.standardtiles.rawhtml">
          <div class="mosaic-tile-content">
              <a href="./@@plone.app.standardtiles.rawhtml/extratext?content=<p>Placeholder</p>"></a>
          </div>
      </div>
```

should this be correct then?

**Comment by agitator** [comment]
but prepolulated text seems to be ignored

**Comment by datakurre** [comment]
That's surprising. I should write a test to prove that. Have you tried with add form? The prepopulated value should be ignored mostly only when there's existing (but even empty) value.

agitator kirjoitti pe joulukuuta 11 11:30:42 2015 GMT+0200:

**Comment by vangheem** [comment]
pre-populated text works with this tile now. Yes, a way to auto switch inline text tiles with richtext when layouts are saved to be centrally managed would be idea here.

For me, even though the performance isn't as well, I only use the "rawhtml" tile that stores it persistently.
