### ISSUE TITLE
Deleting a tile

### ISSUE THREAD

**Issue by tomgross** [plone/plone.app.mosaic#175]
Deleting a tile is now possible with the big red button in the toolbar. Using this involves a lot of mouse action. Having a 'x' in the upper right corner would give better usability.

**Comment by vangheem** [comment]
+1 I was planning on doing this as well.

**Comment by vangheem** [comment]
The edit button click target is too small as well.

**Comment by datakurre** [comment]
Tom Gross wrote:
> Deleting a tile is now possible with the big red button in the toolbar.
> Using this involves a lot of mouse action. Having a 'x' in the upper
> right corner would give better usability.

Is it really? I did that intentionally to eliminate accidental deletions 
(that instead of adding annoying confirmation dialog).

**Comment by vangheem** [comment]
<img width="425" alt="screenshot 2016-03-25 16 40 21 copy" src="https://cloud.githubusercontent.com/assets/524413/14089379/38d14fa2-f4fa-11e5-965f-09a9efb5f03a.png">

What about something like this--a sticky menu that scrolls along with the user so they don't have scroll as far up.

**Comment by hvelarde** [comment]
@datakurre confirmation dialogs for deleting things are never annoying ;-)

**Comment by datakurre** [comment]
@vangheem I agree that scrolling top just to delete a tile is an issue. Sticky / floating menu with a confirmation dialog seems to be ok for all the others, so I don't oppose. (Making the whole top menu sticky (fixed position) would probably only cause new problems.)

**Comment by vangheem** [comment]
I disagree making it a dialog to confirm delete. When users are in custom mode, having a dialog is disrupting to a productive workflow of managing tiles. Maybe the garbage can icon turns into a check icon with cancel to confirm/cancel removal instead.

**Comment by datakurre** [comment]
@vangheem Also I'd prefer it to be without confirm, but then UI needs to be more protective otherwise. How about requiring two clicks?

(The Deco editor had some support for history (undo / redo), but I've never looked into was it really implemented. Also persistent tiles would add some extra work for a such behavior. (plone.app.drafts makes it possible to cancel all edits, but may not make sense for this))

**Comment by davilima6** [comment]
Undo (like Gmail Lab's delayed sending) or some sort of soft delete would be best scenario, since users can also confirm dialogs, click check icons or double click by mistake:
* http://ux.stackexchange.com/questions/71960/deletion-confirm-or-undo-which-is-the-better-option-and-why

However if that's hard, I'd be +1 to @vangheem's suggestion, it's more explicit iiuc.

**Comment by vangheem** [comment]
This is implemented.
