### ISSUE TITLE
Custom tiles appear unstyled in the mosaic editor.

### ISSUE THREAD

**Issue by shadowmint** [plone/plone.app.mosaic#178]
Consider the situation in which you have create a new custom tile 'Video Player'.

This video player is bundled into the package `my.app.videotile`. This package is then installed on the site using the theme `my.app.theme`.  Although `my.app.videotile` provides 'basic' styles for the video player, the video player itself is themed, including buttons, frames, etc. in `my.app.theme`.

We now use the mosaic editor to add a video tile to a page. There are two choices:

**1. We include only the resource bundle from `my.app.videotile` on the edit view.** The video tile is now 'unstyled' when you drag it around the page, and the page preview (customize layout), broadly speaking, contains only *unstyled previews* of the tiles on that view. The draggable tile is also unstyled.

**2. We include both the resource bundle from `my.app.videotile` and `my.app.theme` on the edit view.** The tiles are all styled as they will appear on the site, but the theme's resource bundle interferes with the editor styles (for example, base font size), causing all kinds of chaos with every configuration view.

Is there any solution to this issue?

I have seen the suggestion that you create a *3rd* package, `my.app.tiletheme` this is a subset of the styles 'without side effects' that can be used both in edit and view mode.

However, practically speaking this isn't really feasible. The CSS layout is almost always done relative to base font-size using em/rem to size element which are core the theme itself, and splitting these out into the tile theme package will generate the same side effects.

It seems like the 'mosaic-tile' version of the tile that you see in the edit view will never look exactly like it will on the front end; at which point, why are we trying to render it as if it would?

**Comment by vangheem** [comment]
I don't really understand the problem yet. All custom tiles I write have the same styles in edit view as when they are viewed.

**Comment by shadowmint** [comment]
A theme may (well, practically speaking, do) override the default styles on the tile.

**Comment by acsr** [comment]
If I style e.g. the rows with different width, the markup differs even between view and edit in stock mosaic, because the .row class is missing in the editor and is replaced with a data... structure as an attribute. I need to dieve deeper to give a more detailed wrapup.

If you add additional row styles, you may exceed what an "average" integrator does. E.g. when you need to exceed the basic width of the mosaic container as defined in the basic concept.

**Comment by datakurre** [comment]
That's probably related to the "grid transform" feature and needs some thought.

Mosaic editor syntax differs from the view syntax, because editor saves content in "grid system agnostic" format so that the used grid system could be defined in theme and changed later. Yet, currently p.a.blocks includes adapters only for deco and BS3 grids.

Maybe @bloodbare (who implemented this) had an idea, how the correct grid css could also apply in editor.

**Comment by vangheem** [comment]
We've unified the grid transform so there is no longer any difference between edit and view of layout with grids applied.
