### ISSUE TITLE
Pagination in collection tile leads to unthemed page

### ISSUE THREAD

**Issue by fulv** [plone/plone.app.mosaic#185]
- Plone 5.0.4
- plone.app.tiles = 2.2.1
- plone.app.blocks = 3.1.0
- plone.app.mosaic = 1.0
- plone.app.standardtiles = 1.0
- plone.tiles = 1.5.2
- plone.app.drafts = 1.0

1. Create an "Existing content tile" and select a collection that has more than one batch of items
2. Save the page
3. In the pagination of the collection tile, click one of the links for the following pages

Result:  the following batch in the collection is loaded but it's completely unthemed, and the rest of the page layout is gone, too.  See screenshots.

<img width="281" alt="screen shot 2016-04-17 at 5 15 56 pm" src="https://cloud.githubusercontent.com/assets/460742/14591203/d1547a7a-04c1-11e6-9c63-df276a764f13.png">

<img width="366" alt="screen shot 2016-04-17 at 5 15 27 pm" src="https://cloud.githubusercontent.com/assets/460742/14591206/e28bec1a-04c1-11e6-97bc-b9559472d9ab.png">

The URL of the default mosaic page is:
https://foo.com/fulvio-test

The URL after clicking a pagination link is:
https://foo.com/fulvio-test/@@plone.app.standardtiles.existingcontent/24838332bac24b859140f433d7cc5c42?b_start:int=20&content_uid=dfced8b59f3568fa990f36969a75d65e

**Comment by datakurre** [comment]
@fulv Would it be good enough if the pagination would redirect to collection itself?

**Comment by fulv** [comment]
@datakurre Not ideal, but certainly more acceptable than the current situation.

**Comment by datakurre** [comment]
Is there a pattern for updating paging like that using Ajax? It would fix it for most people.

**Comment by fulv** [comment]
It certainly would, but I honestly don't know.  The structure pattern seems
to paginate with Ajax, but I don't know if that's part of structure, or if
it's a stand-alone pattern that could be used in collections.

**Comment by thet** [comment]
The structure pattern uses it's own batching navigation logic.

@fulv do you have an ``ajax_load=1`` parameter in the links generated by plone.batching? And do you use a plone.batching version < 1.0.6? Then upgrade - since https://github.com/plone/plone.batching/commit/ceca6351f70f9cc4f83f6264b173ed01538e3769 the ajax_load parameter is omitted by default.
If I'm guessing right, this would solve your problem by not redirecting to a unthemed site, but to a collection within the design of your site.

Of course, better would be to also reload the tile via ajax. I've done plone.batching ajax loading  via customizing the plone.batching.batchnavigation.pt template. This is an example for one link entry:

```
      <li tal:attributes="class python:'previous' if batch.has_previous else 'disabled'">
          <a href=""
             class="pat-contentloader"
             tal:define="url python:view.make_link(batch.previouspage)"
             tal:attributes='href url;
                             data-pat-contentloader string:{"url": "${url}&ajax_load=1", "content": "#content", "target": "#content"}'
             >
             &laquo;
          </a>
      </li>
```

But I can imagine that there are smarter ways without customizing the batchnavigation template. Like applying a pattern on the tile wrapper and configuring it so, that all batchnavigation links are loaded via ajax. Just, this pattern doesn't exist yet - pat-contentloader might be extended to support this use case.

**Comment by fulv** [comment]
@thet No, I'm using plone.batching 1.1.0, which I'm guessing comes with Plone 5.0.4.

**Comment by vangheem** [comment]
Easiest fix for this because of how this tile is done right now is here: https://github.com/plone/plone.app.standardtiles/commit/732b77812a62ade324cc2e1e4320014df3e13ef3

This just directs batching to the collection's url.

If you want a more robust tile with batching inline doing js, you'll need to write your own tile. This will not be supported by plone for this release.
