### ISSUE TITLE
allow each tile to have its own settable CSS ID or class

### ISSUE THREAD

**Issue by tkimnguyen** [plone/plone.app.mosaic#205]
...so that a themer can target a specific tile, as per discussion with @RobZoneNet

**Comment by vangheem** [comment]
settable? How about just a class name that is generated based on the tile id?

I don't like how the UI would work if it was settable.

**Comment by RobZoneNet** [comment]
I would prefer it since it would help in making fancy front pages. It would be easier to maintain for responsive design instead of just mosaic-grid-row. 

![screen shot 2016-05-31 at 12 52 48 pm](https://cloud.githubusercontent.com/assets/103745/15683085/a1c7d7c2-272e-11e6-922e-f4b5f8591077.png)

**Comment by vangheem** [comment]
we already have the ability to set custom tile and row classes

**Comment by vangheem** [comment]
format dropdown

**Comment by agitator** [comment]
format classes are kind of generic...
I think what would be useful is classes or ids to mark a row based on its content, for example product-teaser-row, team-presentation-row, ...

**Comment by vangheem** [comment]
I dunno. 1) I don't know how you'd make a sane UI for it, do we stick the field on every tile config? How that that work for rich text 2) it adds a 3rd way to set classes on tiles.

**Comment by RobZoneNet** [comment]
Maybe each time there is a new grid-row somehow make it class name editable.

**Comment by agitator** [comment]
haven't used the most recent mosaic yet ... will again soon ;-) 

question also is if that class/id shouldn't better be on a row/column

**Comment by datakurre** [comment]
Adding CSS ID or class could fix the fancy front-page use case right 
now, but there must be a better way to do it. Fancy pages are very 
closely tied to themes, so probably we should have way to define "tile 
templates" in themes. In the simpliest form, those would be static HTML, 
which would then be editable with TinyMCE. Not sure, though, how to 
combine fancy HTML and application tiles (like image placeholders and 
collections).

I side with @vangheem. As Deco, Mosaic tries to be more generic WYSIWYG 
layout and editing UI than just a front-page tools, and we should try to 
keep it simple. Agreed, though, that it's not quite there yet.

And about rows. Rows are a bit tricky, because Mosaic editor creates and 
removes rows in fly. There was a version of Deco, which had explicit 
rows like in collective.cover, but personally I prefer Mosaic
way of hiding rows from me. Yet, a way to "freeze" a row could be useful 
for the fancy front-page use case.


Rob Porter wrote:

**Comment by djay** [comment]
I thought there was already styles that the themed can add to the theme and
then the editor can apply to a tile or a row. I think that's the best way
of doing this. And editor shouldn't be dealing with CSS class ids

**Comment by tkimnguyen** [comment]
The context of this feature idea is that someone who needs to compose a landing page but isn't a CSS/HTML wizard can use Mosaic, but then the designer / mobile themer who comes in afterwards has to have IDs and classes in the Mosaic page to help him/her target specific tiles. That's the use case...

**Comment by datakurre** [comment]
As @djay said, it's already possible to define and set classes for tiles and rows. The open issues there are the inconvenient registry.xml configuration (we should create a plone.app.theming plugin) and rows disappearing because of implicit row management.

@tkimnguyen Thanks for confirming the use-case. I've been thinking it only the other way around. Since (custom) layouts are just content, the Mosaic Editor is the only blocker. A few sub-issues here:

* layout serialization / deserialization should preserve tiles and row id
* if possible, rows with ids should not be implicitly removed
* UI for adding and editing ids (for the current editor, a format menu action with modal for updating the id would probably be easiest to implement).

**Comment by djay** [comment]
@datakurre what would be better than theming plugin just for mosaics would be an enhancement p.a.theming to be able to create arbitrary categories of css styles. For example you create a mosaic.css, add it to the manifest under 
```
user-selectable-styles =
  tinymce.css
  mosaic.css
```
and then there is a api mosaics can call to get the list of styles and their names. e.g.
```
for name, description, cssclass in plone.app.theming.getSelectableStyles('mosaic'):
  ...
```
