### ISSUE TITLE
PLIP plone.app.mosaic for Plone 5.x

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#212]
At Boston PloneConf it should be clear if, when and how Mosaic could be bundled with some future Plone 5 feature release. Therefore Mosaic should be PLIP'd ASAP, Mephisto Sprint 2016 being the last possible time and place to do that.

**Comment by jensens** [comment]
I would separate this in several better consumable parts:

1. get plone.tiles, plone.app.tiles, plone.app.blocks and plone.app.standardtiles into core - this can happen in the 5.x series. Those packages are stable. Not sure about plone.app.drafts (I think it can go with mosaic).
2. use plone.app.blocks with tiles and layouts as default mechanism to build pages - this is a Plone 6.0 thing and need to be introduced carefully. 
3. get plone.app.mosaic into core - as an core addon this can happen in the 6.x series

**Comment by datakurre** [comment]
Good thoughts. Make sense from stability point of view. But part 1. would be confusing alone, because just "installing the tiles framework" would do nothing. Part 2. would be a lot of work, beause it implies moving portlets and viewlets into tiles, and main template into site layout.

**Comment by jensens** [comment]
To get (1) into a state were it makes sense: I think what is missing are the site-layouts of mosaic.
We're using parts of mosaic in a project at the moment, and its a great advantage. What we're not using is the site-composer (aka mosaic editor). But we're using fixed content layouts a lot and it makes building pages so much easier. It works together with behaviors like a charm.

Part two is in fact the third missing part of what was initially the third D (Dexterity, Diazo, Deco). Thats huge, but it gives us the chance to redefine how definition of UI in Plone works, adds maximum flexibility for integrators and simplifies the whole ecosystem a lot. We would not need viewlets anymore, because then everything is a tile. Portlets (which are in facts a persistent inherited viewlets) should be replaced too (how in details needs some discussion, not because its difficult, but because there are some options).

Mosaic as "the site composer" (or site-builder) for content - and in the long run for the whole site - can be evolved in parallel and consume all those upstream developments.

**Comment by datakurre** [comment]
:+1:

**Comment by djay** [comment]
In terms of the user experience a user would be electing to use mosaic on a given Page? or it would be the only option for a Page? or would it go further and replace Folders and Collections as well?

**Comment by jensens** [comment]
@djay I think the details need to be defined in the upcoming discussions.

**Comment by djay** [comment]
@jensens what upcoming discussions?

**Comment by djay** [comment]
btw, the concept of merging page, collection and folders using tiles is whats analysed in this ticket. https://github.com/plone/Products.CMFPlone/issues/519

**Comment by jensens** [comment]
@djay well, since this is a huge thing I expect that there are some ;) and they just started. Memphisto sprint also addresses this and it would be good to collect needs and user stories before this.

What I (personally) expect at the end of the process is a Plone where our current views are replaced by (static) layouts. I would not like to see everything a composeable page (dynamic layouts), because for at least most of our customers this is not what we need.

I think merging page+collection can work if a collection is a dynamic tile of a composed page (mosaic).

Overall folderish types is imo a good idea anyway and there is already a PLIP which needs some energy. 

I see that we need an overall concept on the UX and the way we create content. But I'd not try to implement it all in one big gulp. We need to define consumable steps, release them early and then move forward for the bigger goal.

**Comment by djay** [comment]
ok. Just checking whats in scope by this proposal. It seems as if the above proposal would likely mean it's at most available as a displayview option on the default Page type and not go any further. That would at least make it possible for someone to configure their site to have a single content type. but they would still be missing functionality unless we fix the additional issues highlighted in https://github.com/plone/Products.CMFPlone/issues/519

**Comment by hvelarde** [comment]
just thinking: how does this fits the split of Plone into two separate components in the future: Plone server and Plone client?

**Comment by jensens** [comment]
@hvelarde well, thats at the moment a rough idea. At least using tiles everywhere would make that much easier.

**Comment by vangheem** [comment]
For those interested, we worked on a roadmap: https://github.com/plone/plone.app.mosaic/wiki

I'm going to close this ticket in favor of the roadmap and the assumption this will not be plip'd for 5 but some future version.

**Comment by hvelarde** [comment]
that was awesome! now I can say we have learned a lot from past mistakes; thank you guys for planning things like that.
