### ISSUE TITLE
Press the save button in mosaic has no effect, no feedback (constraint validation errors in the page)

### ISSUE THREAD

**Issue by rristow** [plone/plone.app.mosaic#290]
Problem
The user click save button in mosaic and nothing happens.

Reason
If the container object (page) has validation errors, e.g. a required fields is empty, the mosaic template couldn’t be saved as well. This is ok, but the problem is that the user has no feedback about what is wrong.
This could happen for example if a behavior with “required fields” is activated to this container.

Workaround
The user must change the view to “default view”, try to save the page, check what is wrong and change again to mosaic view.

**Comment by tomgross** [comment]
This is a major usability pain in Mosaic. Anyone has another workaround or solution as described in the issue?

**Comment by datakurre** [comment]
All errors are available in HTML. The issue is to make them visible:

1. We should display portal message in Mosaic editor
2. We should highlight missing fields (by locating the errors from HTML). The error could be either in properties overlay or already positioned field tile

Part 2 could be simplified by not hiding positioned tiles from properties tab. Unfortunately, for inline-editable fields (text based fields), the synchronizing is only implemented from layout to fields, so those should be somehow disable in properties (or two way synchronization implemented).

**Comment by datakurre** [comment]
I'll try a simple fix: Simply don't launch the Mosaic editor when there is validation errors.
