### ISSUE TITLE
Missing feedback if something goes wrong with saving/retrieving tiles

### ISSUE THREAD

**Issue by tomgross** [plone/plone.app.mosaic#346]
I have a Plone with Mosaic and a Webserver (Apache) chain in front.

Apache limits the size of the URL (including the query string). With very BIG tiles (eg. a big table in plone.app.standardtiles) mosaic refuses to render the tile. In the log you see a reference to _undefined_.

Mosaic should warn the user if something went wrong with save/get tiles. Now such errors are silently ignored.

Plone 5.0.6, plone.app.mosaic 2.0rc4

```
Error handling subrequest to https://webcms0.fhnw.ch/de/studium/wirtschaft/bsc-betriebsoekonomie/unterrichtszeiten/undefined
Traceback (most recent call last):
  File "/webserver/buildouts/common/eggs/plone.subrequest-1.7.0-py2.7.egg/plone/subrequest/__init__.py", line 143, in subrequest
    traversed = request.traverse(path)
  File "/webserver/buildouts/common/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/BaseRequest.py", line 525, in traverse
    return response.notFoundError(URL)
  File "/webserver/buildouts/common/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/HTTPResponse.py", line 718, in notFoundError
    "<p><b>Resource:</b> %s</p>" % escape(entry))
NotFound:   <h2>Site Error</h2>
  <p>An error was encountered while publishing this resource.
  </p>
  <p><strong>Resource not found</strong></p>

  Sorry, the requested resource does not exist.<p>Check the URL and try again.</p><p><b>Resource:</b> https://webcms0.fhnw.ch/de/studium/wirtschaft/bsc-betriebsoekonomie/unterrichtszeiten/undefined</p>
  <hr noshade="noshade"/>

  <p>Troubleshooting Suggestions</p>

  <ul>
  <li>The URL may be incorrect.</li>
  <li>The parameters passed to this resource may be incorrect.</li>
  <li>A resource that this resource relies on may be
      encountering an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>
```

**Comment by datakurre** [comment]
@tomgross Thanks again. There's actually two issues in this. The first one is the issue with too long URLs, the second one is the error.

The error should be fixed in editor.

The first one requires change in how tile URLs are generated. I'm currently working for plone.tiles 2.0, and because we can make breaking changes, I'd drop support for query string from URL generated for named tiles. With named tiles, I mean tiles editable editor, tiles with UUID in @@tiletype/UUID/?querystring. That solely would fix the issue with Mosaic 2.0, because all tiles created with editor save their data into field storage and querystring is only remain from plone.tiles 1.x.

**Comment by datakurre** [comment]
https://github.com/plone/plone.tiles/pull/22/commits/d7802f322ffeda87bd14db5980fa4d69a9bfccb0 should remove querystrings from tile URLs when they are not needed.

(I did not manage to finish editor fixes today. Will continue tomorrow.)

**Comment by tomgross** [comment]
Fixed with https://github.com/plone/plone.app.mosaic/pull/348
