### ISSUE TITLE
Folder contents tile to transient

### ISSUE THREAD

**Issue by bloodbare** [plone/plone.app.mosaic#45]
Move the folder contents tile to be transient

**Comment by datakurre** [comment]
@simahawk 

1. content listing tile should be restored into p.a.standardtiles (it was removed in https://github.com/plone/plone.app.standardtiles/commit/c165fe6bb5826252424f561068f1a45f12cdd3f1)
2. if you just revert comment in 1. changes from https://github.com/plone/plone.app.contentlistingtile/commits/master should be re-applied
3. make sure that the tile is transient (for some reason, too many tiles in p.a.standardtiles are/were persistent for no good reason)

**Comment by datakurre** [comment]
Oops. Did this in https://github.com/plone/plone.app.standardtiles/commit/725e79a6a047605d1a5eb9be90bcf95999a4dbe6 so @simahawk can work on proxy tile.

Also plone.tiles required a few fix, so we need to release plone.tiles 1.4.0 before Mosaic.

**Comment by simahawk** [comment]
@datakurre you did everything! :S :) anyway... I tested it and is working fine. I cannot find any issue on "proxy tile", are you referring to the portlet tile?

**Comment by datakurre** [comment]
@simahawk There's no a spesific issue yet. Just try if Proxy tile works, and when it doesn't try to fix it to work and be transient. I haven't really tested it myself, so I haven't created issue for it. :)

**Comment by datakurre** [comment]
@simahawk Basically we should test (and fix) every tile available in the menu or remove them from the default registry settings.

A good start would be to try them out and file issue for each broken one.

Also, sorry for taking this issue from you :) This was not as trivial as I though, because it required a few extra fixes on how transient tile information was passed and marshalled.

**Comment by datakurre** [comment]
And I should add that this is a quite cool tile ;)
