### ISSUE TITLE
No layouts visible in layouts editor, unable to save custom layout 

### ISSUE THREAD

**Issue by mtrebron** [plone/plone.app.mosaic#510]
In a new Plone 6 Classic install with plone.app.mosaic-3.0.0a6, the layouts editor `@@layouts-editor` does not show the existing layouts. Additionaly and maybe related: attempting to customize and save a custom layout within a Mosaic page fails as the modal window submit button contains no on click event.

When inspecting the pages, there are no visible errors in the browser's developer tools.

![Screenshot from 2022-11-18 13-42-38](https://user-images.githubusercontent.com/14139595/202708335-77ec7648-667c-47fd-8fa5-78683b51070b.png)

![Screenshot from 2022-11-15 15-20-41](https://user-images.githubusercontent.com/14139595/202708418-f4823f05-be69-4647-aa21-2fc87ddf23ef.png)

**Comment by petschki** [comment]
This view relied on mockups `pat-filemanager` which got removed since ES6 update in version 5.0.0 (I think the decision was made because Plone 6 removed TTW theming) ... as a logical consequence mosaic cannot deliver TTW layout template editing anymore as long as someone si willing to backport `pat-filemanager` or something similar for mosaic.
