### ISSUE TITLE
how to achieve a rows/sections?

### ISSUE THREAD

**Issue by djay** [plone/plone.app.mosaic#68]
## User problem

A very popular layout style is similar to this http://preview.oklerthemes.com/porto/3.7.0/index-one-page.html. Dont' know its name but the main content is multiple rows or sections with different styles going down the page, each with a different style and layout.
It's not clear how to achieve this with mosaic.

## Internal

Mosaic seems to support grids rather than some concept of containers which can be styled. collective.cover does support these containing divs. 

## Options

1. One way to achieve it is to somehow compose multiple mosaic pages perhaps via a collection and the "all content view". It's not clear how you would specify the row style however. 

2. could compose multiple mosaic pages using mosaic itself and use the "existing content" tile.

3. introduce a concept of containers like c.cover. Either vertical or horizontal. Allow the user to pick a style. Perhaps could include access controls like c.cover so some people can add into a container but change the containers or add to another container.

4. Using something like tinymcetiles you could support tiles inlined in text. Then you can have tiles within tiles. However then you don't really have nice ways to layout each row. Only tables etc and what tinymce allows.

5. ??

**Comment by agitator** [comment]
As i understand it, what we are missing is some kind of section/container tile to allow to have logical sections of a (larger) composed page. 
This would allow to name a section, have and id/selector to add additional styles and also have jumping points/anchors. A container tile likes this would also make it easier to add advanced styles like parallax effects, since we have logical sections to base them on.

**Comment by datakurre** [comment]
The current editor uses Deco grid, which does have rows / horizontal container. Yet, those rows are created and deleted implicitly and not exposed to user editable UI. Sea Sprint version of Deco added explicit rows, but I'd like to prefer the original design.

It would be almost trivial to add a formatting category and styles for rows, but it would need a bit more work to make those more visible (e.g. labels to be visible during hover).

Yet, the original Deco design probably would prefer site-layout panels as those containers. Any page can have its own site-layout, which could have any number of editable areas called panels anywhere in the layout. The layout editor allows to edit all of them. Those panels could be wrapped into styled containers. 

But we really want to finish content layouts first and only then start to expose site layouts in UI. (We are also completely missing editor for site layouts.)

Panels can have non-removable or even non-editable tiles, but "non-editability" of those are only protected by editor. So, it's not really a protection, but a convenience. Everything is stored in the same layout field, which is protected as whole by cmf.ModifyPortalContent.

Another problem with site layouts are that they must containg everything in html-tag (including head). https://github.com/plone/plone.app.mosaic/issues/35 should bring more flexibility, but I'm still figuring out, how to do it correctly, without too much more performance overhead.

**Comment by datakurre** [comment]
https://www.dropbox.com/s/ga7445mbiwduyfp/Blocks.pdf?dl=0

**Comment by agitator** [comment]
ah! there's a doc for it ;-)

**Comment by djay** [comment]
I've read it before.  I understand deco had a concept of panels but I guess
I don't see a way to insert as many panels as to want via the custom page
layout editor.  Or a way to apply a style to a panel.  Is the only way to
create my own custom page layout manually in portal resources?

**Comment by datakurre** [comment]
That's correct. Page layout editor only allows to edit content in the panels defined in site layout. Because, we don't have site layouts yet, it defaults to main_template with #content id as the main panel.

Currently, more panels can be added only by creating a custom site layout in portal_resources and then activating that site layout from layout tab in portal properties. Yet, layout tab is only visible when custom layout is not selected. At the last Conference we agreed to hide site layouts for now and focus on single panel page layouts at first to get this finally released (and not introducing too many concepts at first).

So, clearly, "site layout story" is far from finished, because Deco sprints never really got that far.

That said, maybe we should introduce "Row" category into formatting menu to allow defining styles for rows similarly to styles.

**Comment by datakurre** [comment]
Oh dear, too bad, not trivial. The editor optimizes the amount of row, which makes it not trivial understand when a new row is created. Also, row styles are not persisted, but rows are generated each time the layout is saved.

So, currently this can be achieved best by creating a new page for each row / section, and adding them into the final page with "External content" tile and applying tile styles.

Maybe something better can be implemented during the upcoming sprints (Anniversary Sprint  and Berlin Mosaic Sprint).

**Comment by djay** [comment]
OK I will try that.

The more I think about it explicit rows and cols like in c. Cover is a nice
feature.  Worth thinking about.

**Comment by datakurre** [comment]
Adding row styles was possible after all. There's still not explicit rows and the automatic row creation / deletion logic may bring surprises, but better than nothing, I'd guess.

![nayttokuva 2015-05-08 kello 5 02 52](https://cloud.githubusercontent.com/assets/160447/7529361/d0dfdf0e-f53f-11e4-9fc2-1ebf241f6445.png)

About explicit rows and columns. Probably there were reasons, why Sea Sprint decided to add them. Yet, I still kind of like the original design (and it's probably not an accident either), which gives faster start. It needs to be thought as whole with the possible "site layout editor".

**Comment by djay** [comment]
I think this just might work for my purposes. Nice idea. It means diazo can be applied to make the row appear very different, even vertical if need be so this does add a lot of flexibility. Nice.
