### ISSUE TITLE
Text tile editor is missing "Insert link" action

### ISSUE THREAD

**Issue by datakurre** [plone/plone.app.mosaic#85]
@thet You are quite familiar with the new mockup pattern based TinyMCE integration for Plone. What would it require to add Plone's "Insert link" action (and dialog) into a custom TinyMCE -configuration?

(Probably Mosaic should also somewhat use Plone's global TinyMCE configuration, but that may include surprises, which I don't want to face just now. Mosaic has very tight integration with TinyMCE, different text tile types may have different available TinyMCE actions, and generally the configuration is abstracted to be independent from TinyMCE to make it replaceable, when better mature alternative appears.)

**Comment by datakurre** [comment]
@martior I thought this to be trivial, but it appears that the new "plonelink" plugin is everything but easy to use outside the default TinyMCE pattern (Mosaic manager manages its TinyMCE editors by itself for customizable UI and because there are many of them) . It's possible, but probably requires days.

**Comment by datakurre** [comment]
Did have to mock tinymcepattern, but luckily not too much.

 * [ ] Modal labels (should be translatable) are empty on Plone 4 (Plone 5 not yet tested)
 * [ ] unlink action is still missing

**Comment by djay** [comment]
Maybe we are taking the wrong approach. The reason linking is hard is because you are trying to combine the text menus with the tile menus into a single menu at the top right @datakurre?

But if you think about it, it might not make as much sense as we think it does. Half of the insert/format menu relates only when inside a text box. The other only relates to blocks as a whole, such as styling a block/row or inserting another kind of tile. We aren't supporting inserting tiles inside text tiles.

So perhaps we can simplify this whole thing by using tinymce as we normally do, with its own ribbon and menus. But we can make it slide up on top on the edit control. This is supported out of the box with tinymce - http://www.tinymce.com/tryit/inline.php
This also makes it closer to the medium editor as shown by @pigeonflight - https://community.plone.org/t/mosaic-the-new-layout-solution-for-plone/548/30

This also important because a bunch of other plugins customise tinymce and they won't work if we have too much of a custom tinymce for mosaic.

**Comment by datakurre** [comment]
@djay Re-using the LinkModal code from TinyMCE pattern required extra work, because we are not using TinyMCE pattern. Re-using the pattern is hard (and not a fit way), because mosaic creates a lot of TinyMCE editors in fly.

Replacing format menu with TinyMCE inline toolbars is probably a good idea. I did as ask Rob, why they chose top menu instead of inline menus, and it was just a matter of taste back then.

**Comment by datakurre** [comment]
@martior Just as an update for you. Branch ``datakurre-link-action`` has working link action (button), but not yet unlink button (should be trivial add, though). Finishing this would probably also require fixing https://github.com/plone/plone.app.mosaic/issues/100 to not show resolveUid links for the end user. The latter is not hard either. It's mostly copy & paste & adapt portal transform execution code from plone.app.textfield.

Yet, I try my best to not work on Mosaic for the rest of the summer :). If someone would like to, I should be able to help with it, though.
