### ISSUE TITLE
Preview action

### ISSUE THREAD

**Issue by tomgross** [plone/plone.app.mosaic#99]
A preview (primary?) action would be handy.
As an editor I probably want to preview the changes I made before I submit them. Like with TinyMCE it is not possible to follow links in edit mode with Mosaic. This could be solved with a preview showing a view in its final (anonymous?) state.

**Comment by datakurre** [comment]
@tomgross Good idea. Thanks. Keep posting these :)

Technically, this could be easy to do with p.a.drafting (unless the editor is refactored much that this becomes easier otherwise). The server already stores a draft of the current state of edited page, so we simply need a view, which shows draft data instead of the real data. (And a button, which first posts the latest data and then opens the server rendered preview with that data.)

**Comment by djay** [comment]
Here is a gif of what live sidebyside preview could look like (from another CMS) from https://github.com/plone/Products.CMFPlone/issues/907

![craft-live-preview](https://cloud.githubusercontent.com/assets/41700/18159557/76e7a992-7053-11e6-85c5-c61f025cb99f.gif)

Note this idea could be implemented in plone independent of mosaic, and is still useful for mosaic as it will never be completely WYSIWYG.
